### ISSUE TITLE
autofix-ci/action failed due to `fatal: couldn't find remote ref refs/pull/*/head`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [autofix-ci/action#23]
autofix-ci/action failed due to `fatal: couldn't find remote ref refs/pull/*/head` in some pull requests created by Renovate.

https://github.com/lintnet/lintnet.github.io/actions/runs/14117851840/job/39552170367?pr=673

```yaml
- uses: autofix-ci/action@2891949f3779a1cafafae1523058501de3d4e944 # v1.3.1
```

```
/usr/bin/git fetch --depth=1 origin +refs/pull/673/head
fatal: couldn't find remote ref refs/pull/673/head
Error: The process '/usr/bin/git' failed with exit code 128
```

- https://github.com/aquaproj/aquaproj.github.io/actions/runs/14118562480/job/39554300329?pr=1457
- https://github.com/aquaproj/aqua-renovate-config/actions/runs/14117861284/job/39552198255?pr=858

I'm looking into the cause.
Before running `autofix-ci/action`, `actions/checkout` was run.

https://github.com/lintnet/lintnet.github.io/blob/134d2749e35f92bdb7159e782dad6cf24af2d688/.github/workflows/autofix.yaml#L11-L13

So I think `refs/pull/*/head` should have been fetched, but actually `git fetch` failed due to `fatal: couldn't find remote ref refs/pull/*/head`.

**Comment by suzuki-shunsuke** [comment]
```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +615181329e1c2e5a23a39a647290cdae5f85fe38:refs/remotes/pull/673/merge
```

Ah, I see.
We should checkout not head but merged commit.

```yaml
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{github.head_ref}}
          persist-credentials: false
```
