### ISSUE TITLE
how to change [autofix.ci] commit message

### ISSUE THREAD

**Issue by productdevbook** [autofix-ci/action#4]
example: [autofix.ci] -> fix:

**Comment by mhils** [comment]
I've added server-side support for customization. 😃 Could you check if the following works for you?

```yaml
- uses: autofix-ci/action@commit-message
  with:
    commit-message: "fix: apply automated changes"
```
