### ISSUE TITLE
feature request: add output to check whether files changed

### ISSUE THREAD

**Issue by scarf005** [autofix-ci/action#6]
it'd would be great to run additional action if some files changed, like in https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#outputs

## Example usage

```yaml
# ...
      - uses: autofix-ci/action@8caa572fd27b0019a65e4c695447089c8d3138b9
        id: autofix
        if: ${{ always() }}

      - uses:
        if: steps.autofix.outputs.changes_detected == 'true'
        run: peter-evans/create-or-update-comment@v3
        with:
          body: |
            ...
```
