### ISSUE TITLE
`comment` field not working

### ISSUE THREAD

**Issue by scarf005** [autofix-ci/action#9]
i tried https://github.com/autofix-ci/action/pull/7 in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3395, however they doesn't seem to run, for example like in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3673. despite autofix.ci making commits, it wouldn't add comments.

we're using [latest version of the action](https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/6871967290/job/18689675355?pr=3673).
```yml
      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
        if: ${{ always() }}
        with:
          commit-message: "style(autofix.ci): automated formatting"
          commment: |
            The Autofix app has automatically formatted this Pull Request.

            If you edit your PR on web UI, you can ignore this message.
            If you edit your PR locally, YOU MUST DO EITHER OF THE FOLLOWING:

            - Run `git pull` to merge the automated commit into your local copy of the PR branch.
            - [Format your code locally](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style), and force push to your PR branch.

            If you don't do this, your following work will be based on the old commit, and cause MERGE CONFLICT.
```
